INSERT INTO Estados(sigla, estado) VALUES('AC', 'Acre');
INSERT INTO Estados(sigla, estado) VALUES('AL', 'Alagoas');
INSERT INTO Estados(sigla, estado) VALUES('AP', 'Amapa');
INSERT INTO Estados(sigla, estado) VALUES('AM', 'Amazonas');
INSERT INTO Estados(sigla, estado) VALUES('BA', 'Bahia');
INSERT INTO Estados(sigla, estado) VALUES('CE', 'Ceara');
INSERT INTO Estados(sigla, estado) VALUES('DF', 'Distrito Federal');
INSERT INTO Estados(sigla, estado) VALUES('ES', 'Espirito Santo');
INSERT INTO Estados(sigla, estado) VALUES('GO', 'Goias');
INSERT INTO Estados(sigla, estado) VALUES('MA', 'Maranhao');
INSERT INTO Estados(sigla, estado) VALUES('MT', 'Mato Grosso');
INSERT INTO Estados(sigla, estado) VALUES('MS', 'Mato Grosso do Sul');
INSERT INTO Estados(sigla, estado) VALUES('MG', 'Minas Gerais');
INSERT INTO Estados(sigla, estado) VALUES('PA', 'Para');
INSERT INTO Estados(sigla, estado) VALUES('PB', 'Paraiba');
INSERT INTO Estados(sigla, estado) VALUES('PR', 'Parana');
INSERT INTO Estados(sigla, estado) VALUES('PE', 'Pernambuco');
INSERT INTO Estados(sigla, estado) VALUES('PI', 'Piaui');
INSERT INTO Estados(sigla, estado) VALUES('RJ', 'Rio de Janeiro');
INSERT INTO Estados(sigla, estado) VALUES('RN', 'Rio Grande do Norte');
INSERT INTO Estados(sigla, estado) VALUES('RS', 'Rio Grande do Sul');
INSERT INTO Estados(sigla, estado) VALUES('RO', 'Rondonia');
INSERT INTO Estados(sigla, estado) VALUES('RR', 'Roraima');
INSERT INTO Estados(sigla, estado) VALUES('SC', 'Santa Catarina');
INSERT INTO Estados(sigla, estado) VALUES('SP', 'Sao Paulo');
INSERT INTO Estados(sigla, estado) VALUES('SE', 'Sergipe');
INSERT INTO Estados(sigla, estado) VALUES('TO', 'Tocantins');
